### ISSUE TITLE
Can't log in on Zeppelin

### ISSUE THREAD

**Issue by m4ttw4n** [tevgeniou/RegressionApp#2]
Hello,

I can't seem to log in with my INSEAD credentials on Zeppelin after "opening" my workstation. It just says that my username and password doesn't match. I've tried different variations for username (matt.wan, matt.wan@insead, matt-wan, etc.) and it still doesn't seem to work.

Any help would be appreciated!

Thanks,

Matt

**Comment by vkapartzianis** [comment]
In general, the following may help you when you have trouble logging in:

* Make sure you enter your username as firstname.lastname (omit the @insead.edu domain as it's appended by default).
* Wait a bit. Your host doesn't have any user info store locally, it has to contact INSEAD servers to check your credentials and connection problems may get in the way.
* Disable two-factor authentication if you've set it up for your account. Only plain (user/password) authentication is supported at this point.

In addition, your account may not have permission to use the app. User permissions are set in the INSEAD directory too -- we have to verify such cases manually and coordinate with INSEAD IT to resolve them.

**Comment by vkapartzianis** [comment]
I checked and user `matt.wan` (i.e. you) doesn't seem to have the required permission to use the app. I sent an e-mail to INSEAD IT about it.

Anyone else having the same problem, please comment here, mentioning your INSEAD username.

**Comment by shomechhabria** [comment]
I am having the same problem. My INSEAD username is shome.chhabria

**Comment by ahrumpak** [comment]
I am having the same problem as well. My INSEAD username is ahrum.pak

**Comment by m4ttw4n** [comment]
@vkapartzianis I tried logging again just now, and it looks like I still don't have permission / the login doesn't work. Thanks for the help!

**Comment by vkapartzianis** [comment]
I'm sorry for the delay. We're still trying to resolve this with INSEAD IT.

**Comment by harikabra** [comment]
I am having the same problem. My INSEAD username is hari.kabra

**Comment by vkapartzianis** [comment]
Anyone having this problem, please follow the steps below, as a temporary measure, to grant the necessary permissions manually for your account. We'll hopefully resolve this for everyone in the next 24 hours.

1.  Login with your INSEAD credentials at https://portal.azure.com
2.  Go to Azure Active Directory -> App registrations and select to see "All apps" in the dropdown filter type.
![image](https://user-images.githubusercontent.com/1918344/36396548-7106e838-15c7-11e8-96e9-228fe7c34337.png)
3.  Go to "Zepelin-native" -> Settings -> Required permissions
4.  Click "Grant Permissions"
![image](https://user-images.githubusercontent.com/1918344/36396634-c816768e-15c7-11e8-86e8-f107c98dd0e7.png)

**Comment by vkapartzianis** [comment]
Please note that the above is just an optional, temporary measure, in order to speed up the process. An INSEAD administrator will grant the required permissions on behalf of all affected users, in any case.

**Comment by vkapartzianis** [comment]
We believe we have resolved the issue for all affected users. Can you please try again and let us know if any problems still persist?

**Comment by m4ttw4n** [comment]
I can confirm that the issue is resolved for me now.
